### ISSUE TITLE
Build Instruction

### ISSUE THREAD

**Issue by RonSv** [Jason-Carter/GnuCash2Qif#1]
Hello.

Great idea! Faced the same problem, i want to leave GnuCash. 

Can this be used somehow? I would like a brief instruction on how to build it... Thank you.

**Comment by jason-carter** [comment]
Hi RonSv

Thanks. It can be used, but at the moment only if you can compile the project and run it from debug mode or the command line. I'm just about to go away for a couple of weeks holiday, but will create a package and better instructions for it when I return so that it's easier to use.


If you're happy running compiling yourself, just load the GnuCashSql2Qif.sln solution into Visual Studio and either:


  1. Compile and debug within Visual Studio. You will need to set the Application arguments of the Debu tab in the properties window of the GnuCashSql2Qif project to:

`  -d "C:/accounts.sql.gnucash.sqlite" -o "C:/output.qif"`

  (Change the paths to whatever folder you wish to use)

  2. Compile the solution and in the command line change to the following directory of your solution:

`GnuCashSql2Qif\bin\Debug\netcoreapp2.1`

  Then run 

`dotnet GnuCashSql2Qif.dll -d "C:/accounts.sql.gnucash.sqlite" -o "C:/output.qif"`

  (Again change the paths to whatever folder you wish to use).

If the above doesn't mean anything to you then apologies, and I will create an easier to use package later.

Kind regards
Jason

**Comment by jason-carter** [comment]
Have added some build and usage instructions to the readme file, which are hopefully easier to follow than my previous comment.

Many thanks for your interest.
Jason
